Starting test with workers=128
Launched task.. waiting
Result : uname_result(system='Linux', node='exp-5-44', release='4.18.0-477.15.1.el8_8.x86_64', version='#1 SMP Wed Jun 28 15:04:18 UTC 2023', machine='x86_64')
Traceback (most recent call last):
  File "/home/vhayot/flox_experiments/test.py", line 125, in <module>
    test_sequence(num_workers=int(args.nodes) * int(args.workers_per_node),
  File "/home/vhayot/flox_experiments/test.py", line 58, in test_sequence
    connector = FileConnector(store_dir='/home/vhayot/flox_experiments/data')
                ^^^^^^^^^^^^^
NameError: name 'FileConnector' is not defined. Did you mean: 'RedisConnector'?
